services:
  adfinalproject:
    build:
      context: .
    container_name: adfinalproject-service
    ports:
      - "9000:80"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: adfinalproject-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: ad_final_project_db
    ports:
      - "27111:27017"
    volumes:
      - adfinalproject-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: adfinalproject-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ad_final_project_db
    ports:
      - "5112:5432"
    volumes:
      - adfinalproject-postgresql:/data/db/postgresql

volumes:
  adfinalproject-mongodb:
    driver: local
  adfinalproject-postgresql:
    driver: local