<?php

return [
    [
        'customer_code' => 'CUST001',
        'company_name' => 'SINthesize Corp',
        'first_name' => 'Marcus',
        'last_name' => 'Chen',
        'email' => 'marcus.chen@sinthesize.corp',
        'phone' => '+1-555-CYBER-01',
        'address_line1' => '2077 Neon Boulevard',
        'address_line2' => 'Suite 404',
        'city' => 'Neo Tokyo',
        'state' => 'CA',
        'postal_code' => '90210',
        'country' => 'USA',
        'customer_type' => 'corporate',
        'credit_limit' => 50000.00,
        'total_orders' => 12,
        'total_spent' => 35750.50,
        'is_active' => true,
        'notes' => 'VIP Corporate Customer - Neural Enhancement Division'
    ],
    [
        'customer_code' => 'CUST002',
        'company_name' => 'CyberTech Industries',
        'first_name' => 'Luna',
        'last_name' => 'Rodriguez',
        'email' => 'luna.rodriguez@cybertech.ind',
        'phone' => '+1-555-TECH-02',
        'address_line1' => '1337 Digital Street',
        'address_line2' => null,
        'city' => 'Chrome City',
        'state' => 'TX',
        'postal_code' => '75001',
        'country' => 'USA',
        'customer_type' => 'corporate',
        'credit_limit' => 25000.00,
        'total_orders' => 8,
        'total_spent' => 18999.99,
        'is_active' => true,
        'notes' => 'Bulk order specialist for energy systems'
    ],
    [
        'customer_code' => 'CUST003',
        'company_name' => null,
        'first_name' => 'Jake',
        'last_name' => 'Morrison',
        'email' => 'jake.morrison@netrunner.mail',
        'phone' => '+1-555-RUNNER-3',
        'address_line1' => '88 Underground Avenue',
        'address_line2' => 'Basement Level',
        'city' => 'Night City',
        'state' => 'NY',
        'postal_code' => '10001',
        'country' => 'USA',
        'customer_type' => 'individual',
        'credit_limit' => 5000.00,
        'total_orders' => 25,
        'total_spent' => 12450.75,
        'is_active' => true,
        'notes' => 'Frequent buyer of neural upgrades and bio-mods'
    ],
    [
        'customer_code' => 'CUST004',
        'company_name' => null,
        'first_name' => 'Aria',
        'last_name' => 'Blackwood',
        'email' => 'aria.blackwood@shadow.net',
        'phone' => '+1-555-SHADOW-4',
        'address_line1' => '404 Error Street',
        'address_line2' => null,
        'city' => 'Data Haven',
        'state' => 'WA',
        'postal_code' => '98001',
        'country' => 'USA',
        'customer_type' => 'individual',
        'credit_limit' => 7500.00,
        'total_orders' => 15,
        'total_spent' => 8999.25,
        'is_active' => true,
        'notes' => 'Prefers stealth and security modifications'
    ],
    [
        'customer_code' => 'CUST005',
        'company_name' => 'Neon Dynamics LLC',
        'first_name' => 'Viktor',
        'last_name' => 'Petrov',
        'email' => 'viktor.petrov@neondynamics.llc',
        'phone' => '+1-555-NEON-05',
        'address_line1' => '3033 Hologram Highway',
        'address_line2' => 'Floor 42',
        'city' => 'Cyber Angeles',
        'state' => 'CA',
        'postal_code' => '90028',
        'country' => 'USA',
        'customer_type' => 'corporate',
        'credit_limit' => 75000.00,
        'total_orders' => 6,
        'total_spent' => 45200.00,
        'is_active' => true,
        'notes' => 'Large scale orders for vehicle enhancement systems'
    ],
    [
        'customer_code' => 'CUST006',
        'company_name' => null,
        'first_name' => 'Zara',
        'last_name' => 'Nova',
        'email' => 'zara.nova@quantum.grid',
        'phone' => '+1-555-NOVA-06',
        'address_line1' => '777 Quantum Lane',
        'address_line2' => null,
        'city' => 'Neo Francisco',
        'state' => 'CA',
        'postal_code' => '94101',
        'country' => 'USA',
        'customer_type' => 'individual',
        'credit_limit' => 3500.00,
        'total_orders' => 9,
        'total_spent' => 3299.99,
        'is_active' => true,
        'notes' => 'Young entrepreneur, focuses on entry-level enhancements'
    ],
    [
        'customer_code' => 'CUST007',
        'company_name' => 'Binary Solutions Inc',
        'first_name' => 'Dante',
        'last_name' => 'Cross',
        'email' => 'dante.cross@binary.solutions',
        'phone' => '+1-555-BINARY-7',
        'address_line1' => '1010 Code Street',
        'address_line2' => 'Development Wing',
        'city' => 'Silicon Valley 2.0',
        'state' => 'CA',
        'postal_code' => '95014',
        'country' => 'USA',
        'customer_type' => 'corporate',
        'credit_limit' => 40000.00,
        'total_orders' => 18,
        'total_spent' => 29800.50,
        'is_active' => true,
        'notes' => 'R&D department for neural interface development'
    ],
    [
        'customer_code' => 'CUST008',
        'company_name' => null,
        'first_name' => 'Maya',
        'last_name' => 'Storm',
        'email' => 'maya.storm@electric.dreams',
        'phone' => '+1-555-STORM-08',
        'address_line1' => '2525 Lightning Road',
        'address_line2' => null,
        'city' => 'Thunder Bay',
        'state' => 'FL',
        'postal_code' => '33101',
        'country' => 'USA',
        'customer_type' => 'individual',
        'credit_limit' => 6000.00,
        'total_orders' => 11,
        'total_spent' => 5699.75,
        'is_active' => false,
        'notes' => 'Account suspended - payment issues resolved, reactivation pending'
    ]
];
