<?php

return [
    [
        'name' => 'SynthCell Battery Pack',
        'description' => 'High-capacity neural energy storage unit for extended cybernetic operations',
        'category' => 'Energy Systems',
        'price' => 899.99,
        'cost' => 450.00,
        'sku' => 'SYN-BAT-001',
        'stock_quantity' => 45,
        'weight' => 2.5,
        'is_active' => true,
    ],
    [
        'name' => 'IonFuel Vials',
        'description' => 'Premium-grade ionic fuel for high-performance neural processors',
        'category' => 'Consumables',
        'price' => 149.99,
        'cost' => 75.00,
        'sku' => 'ION-FUEL-002',
        'stock_quantity' => 120,
        'weight' => 0.3,
        'is_active' => true,
    ],
    [
        'name' => 'OverDrive Capsule',
        'description' => 'Temporary neural enhancement boost for critical situations',
        'category' => 'Enhancement',
        'price' => 299.99,
        'cost' => 150.00,
        'sku' => 'OVR-CAP-003',
        'stock_quantity' => 80,
        'weight' => 0.1,
        'is_active' => true,
    ],
    [
        'name' => 'IonPulse Byte',
        'description' => 'Advanced data processing unit with quantum encryption',
        'category' => 'Data Systems',
        'price' => 1999.99,
        'cost' => 1000.00,
        'sku' => 'ION-BYTE-004',
        'stock_quantity' => 25,
        'weight' => 0.8,
        'is_active' => true,
    ],
    [
        'name' => 'Neuroplasticity',
        'description' => 'Brain augmentation system for enhanced cognitive abilities',
        'category' => 'Neural Upgrades',
        'price' => 4999.99,
        'cost' => 2500.00,
        'sku' => 'NEU-PLAS-005',
        'stock_quantity' => 12,
        'weight' => 1.2,
        'is_active' => true,
    ],
    [
        'name' => 'Tesla Node',
        'description' => 'Electromagnetic field generator for personal defense systems',
        'category' => 'Defense',
        'price' => 3499.99,
        'cost' => 1750.00,
        'sku' => 'TES-NODE-006',
        'stock_quantity' => 18,
        'weight' => 3.8,
        'is_active' => true,
    ],
    [
        'name' => 'Synthlung Upgrade',
        'description' => 'Artificial respiratory enhancement for toxic environment survival',
        'category' => 'Body Modifications',
        'price' => 7899.99,
        'cost' => 3950.00,
        'sku' => 'SYN-LUNG-007',
        'stock_quantity' => 8,
        'weight' => 2.1,
        'is_active' => true,
    ],
    [
        'name' => 'IonPulse Spine Mk. VI',
        'description' => 'Next-generation spinal neural interface with haptic feedback',
        'category' => 'Neural Interface',
        'price' => 24999.99,
        'cost' => 12500.00,
        'sku' => 'ION-SPINE-008',
        'stock_quantity' => 3,
        'weight' => 4.5,
        'is_active' => true,
    ],
    [
        'name' => 'NeuroSpark Node',
        'description' => 'Synaptic acceleration module for lightning-fast reflexes',
        'category' => 'Performance',
        'price' => 6799.99,
        'cost' => 3400.00,
        'sku' => 'NEU-SPARK-009',
        'stock_quantity' => 15,
        'weight' => 1.8,
        'is_active' => true,
    ]
];