<?php
return [
    [
        'username' => 'k.tanaka',
        'first_name' => 'Kenji',
        'last_name' => 'Tanaka',
        'password' => 'SynthNet#2087!',
        'corporate_id' => 'SYNTH-EXE-001',
        'role' => 'Chief Executive Officer',
        'department' => 'Executive',
        'security_clearance' => 'omega',
        'neural_link_id' => 'NL-OMEGA-7749',
        'augmentation_level' => 5,
        'contact_frequency' => 'encrypted',
        'status' => 'active'
    ],
    [
        'username' => 'dr.vex',
        'first_name' => 'Victoria',
        'last_name' => 'Vex',
        'password' => 'AugmentTech!9987',
        'corporate_id' => 'SYNTH-RND-007',
        'role' => 'Head of Augmentation Research',
        'department' => 'R&D',
        'security_clearance' => 'classified',
        'neural_link_id' => 'NL-CLAS-8834',
        'augmentation_level' => 4,
        'contact_frequency' => 'quantum',
        'status' => 'active'
    ],
    [
        'username' => 'c.matrix',
        'first_name' => 'Cypher',
        'last_name' => 'Matrix',
        'password' => 'EnergyCore@2087',
        'corporate_id' => 'SYNTH-ENG-042',
        'role' => 'Energy Systems Engineer',
        'department' => 'Engineering',
        'security_clearance' => 'high',
        'neural_link_id' => 'NL-HIGH-5521',
        'augmentation_level' => 3,
        'contact_frequency' => 'secure',
        'status' => 'active'
    ],
    [
        'username' => 'n.steel',
        'first_name' => 'Nova',
        'last_name' => 'Steel',
        'password' => 'SalesForce#2087',
        'corporate_id' => 'SYNTH-SAL-156',
        'role' => 'Corporate Sales Director',
        'department' => 'Sales',
        'security_clearance' => 'corporate',
        'neural_link_id' => 'NL-CORP-3312',
        'augmentation_level' => 2,
        'contact_frequency' => 'standard',
        'status' => 'active'
    ],
    [
        'username' => 'z.proxy',
        'first_name' => 'Zara',
        'last_name' => 'Proxy',
        'password' => 'SecureNet!4455',
        'corporate_id' => 'SYNTH-SEC-089',
        'role' => 'Security Specialist',
        'department' => 'Security',
        'security_clearance' => 'high',
        'neural_link_id' => 'NL-HIGH-6677',
        'augmentation_level' => 4,
        'contact_frequency' => 'encrypted',
        'status' => 'active'
    ],
    [
        'username' => 'r.byte',
        'first_name' => 'Rex',
        'last_name' => 'Byte',
        'password' => 'LogisticsNet@87',
        'corporate_id' => 'SYNTH-LOG-234',
        'role' => 'Logistics Coordinator',
        'department' => 'Operations',
        'security_clearance' => 'standard',
        'neural_link_id' => 'NL-STD-1123',
        'augmentation_level' => 1,
        'contact_frequency' => 'standard',
        'status' => 'active'
    ],
    [
        'username' => 'a.chrome',
        'first_name' => 'Aria',
        'last_name' => 'Chrome',
        'password' => 'QualityCtrl#2087',
        'corporate_id' => 'SYNTH-QC-078',
        'role' => 'Quality Control Analyst',
        'department' => 'Quality Assurance',
        'security_clearance' => 'standard',
        'neural_link_id' => 'NL-STD-4456',
        'augmentation_level' => 2,
        'contact_frequency' => 'standard',
        'status' => 'active'
    ],
    [
        'username' => 'j.nexus',
        'first_name' => 'Jax',
        'last_name' => 'Nexus',
        'password' => 'NetworkAdmin!99',
        'corporate_id' => 'SYNTH-IT-191',
        'role' => 'Network Administrator',
        'department' => 'IT',
        'security_clearance' => 'high',
        'neural_link_id' => 'NL-HIGH-7788',
        'augmentation_level' => 3,
        'contact_frequency' => 'secure',
        'status' => 'active'
    ],
    [
        'username' => 'l.volt',
        'first_name' => 'Luna',
        'last_name' => 'Volt',
        'password' => 'FinanceCore@87',
        'corporate_id' => 'SYNTH-FIN-145',
        'role' => 'Financial Analyst',
        'department' => 'Finance',
        'security_clearance' => 'corporate',
        'neural_link_id' => 'NL-CORP-9901',
        'augmentation_level' => 1,
        'contact_frequency' => 'standard',
        'status' => 'active'
    ],
    [
        'username' => 'x.shadow',
        'first_name' => 'Xavier',
        'last_name' => 'Shadow',
        'password' => 'BlackOps#2087!',
        'corporate_id' => 'SYNTH-BLK-000',
        'role' => 'Special Operations',
        'department' => 'Black Operations',
        'security_clearance' => 'black-ops',
        'neural_link_id' => 'NL-BLKOPS-0001',
        'augmentation_level' => 5,
        'contact_frequency' => 'dark',
        'status' => 'active'
    ]
];